action_type: Triggered
class: tactician
content: "\n*Under your direction, an ally waits for just the right moment to strike.*\n\n| **Ranged**       |       **Triggered** |\n|------------------|--------------------:|\n| **\U0001F4CF Ranged 10** | **\U0001F3AF One creature** |\n\n**Trigger:** The target moves.\n\n**Effect:** At any time during the target's movement, one ally can make a free strike against them.\n\n**Spend 1 Focus:** If the target has R < AVERAGE, they are slowed (EoT)."
distance: Ranged 10
effect: At any time during the target's movement, one ally can make a free strike against them.
flavor: Under your direction, an ally waits for just the right moment to strike.
keywords:
    - Ranged
level: "1"
name: Overwatch
scc: mcdm.heroes.v1/feature.ability.tactician.level-1/overwatch
spend: '1 Focus: If the target has R < AVERAGE, they are slowed (EoT).'
subtype: triggered
target: One creature
trigger: The target moves.
type: ability
